### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Markets Views
# description: This will be meta HTML tag content. This can be ignored.
description: Visões de Mercados
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: "/"

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Markets Views
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Visões de Mercados
# email: Your E-Mail address for the email button.
email: mail@marketsviews.info
newsletter: https://eepurl.com/haI8rr
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
telegram_username: marketsviews
facebook_username: marketsviews
instagram_username: marketsviews
linkedin_username: marketsviews
twitter_username: marketsviews

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: Sobre Nós
# about_me_description: This will be displayed under the title.
about_me_description: Esses artigos monitoram e interpretam os mercados, fornecendo atualizações e percepções que refletem um prisma de perspectivas em todas as classes de ativos.

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Nossas Recomendações
aviso_title: Nesse lugar você não vai pegar todas as oportunidades, eu não te garanto lucro nenhum. O que te garanto é que se você estudar e seguir as recomendações você vai perder o mínimo possível.
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
tlg_link: https://t.me/marketsviews

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contato
# contact_description: This will be displayed under the title.
contact_description: Entre em contato conosco através das nossas redes sociais

# SIGNUP SECTION
show_signup_card: true
sign_up_title: Newsletter
sign_up_description: Assine o boletim informativo para receber recomendações exclusivas!

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: marketsviews/marketsviews.github.io
# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
